import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter} from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home() {

  const router = useRouter();

  const handleSubmit = event => {
    event.preventDefault();

    const color_redirect = event.target.color_code.value;
    console.log(color_redirect)

    router.push('/' + color_redirect);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Hex Color Picker
        </h1>

        <p className={styles.description}>
          Get started by typing in a color below.
        </p>

        <div className={styles.container}>
          <div className={styles.card}>
            <form
            onSubmit={handleSubmit}>
              <label htmlFor="color_code">Color Code</label>
              <textarea
                name="color_code"
                placeholder="FFFFFF"
                id="color_code"
                rows={1} 
              />
              <button
                type="submit"
              >Grab that color!</button>
            </form>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
